const homeMessage = {

    overview: "Overview",
    types: "Types",
    benefits: "Benefits",
    explore: "Explore",
    eligibility: "Eligibility",
    brands: "Brands",
    categories: "Categories",
    definitions: "Definitions",
    financialOverview: "Financial planning is a step-by-step approach to meet individual financial goals. A financial plan acts as a guide as you go through life’s journey. Essentially, it helps you be in control of your income, expenses, investments, and loans such that you can manage your money and achieve your goals. You need to have an adequate amount of money to fulfil your goals and desires. More importantly, you need to have money at the right point in time. This is where financial planning becomes essential. An individual can complete professional financial planning through certified financial planners from the financial planning standards board India.",
    financialType1: "The rise in the price of everyday items means that if you want to maintain or increase your current standard of living in the future, you need to create a sufficient corpus of wealth. You may also want to purchase a better car or a new house in the future. All this requires money, and it merely highlights the importance of wealth creation. It is possible to achieve these goals by carefully investing your money in the right avenues.",
    financialType2: "Your retirement maybe 25 or 30 years in the future. But that does not mean you plan for it when you retire. To enjoy a happy and comfortable retired life, you need to start building your safety net right now. Planning at an early stage in life can help secure your future against financial uncertainties. Also, you invest lesser amounts if you start early and gain from the power of compounding which helps to build a large enough corpus over the 25-30 year period.",
    financialType3: "Education has become very expensive, not only in India but across the world. And in the future, this cost is only going to rise. This is why it is necessary to start planning from the moment your child is born. Calculate how much you wish to earn and start investing in long-term investment avenues that can help you achieve this goal. You can approach a financial advisor for advice if you are not sure how to proceed further.",
    financialType4: "Every year, you are probably paying a substantial amount as tax. But you can now lower your tax outgo legally. The Indian Income Tax Act provides various provisions for people to reduce their tax outgo. By planning your taxes in advance, you can identify the best avenues to invest your money and reduce your taxable income. Mutual funds provide a tax-efficient avenue for investing for your life goals.",
    typeHeader1: "Wealth Creation:",
    typeHeader2: "Retirement planning:",
    typeHeader3: "Child's Education:",
    typeHeader4: "Saving tax:",
    financialBenefits1: "It may be possible to save money without having a financial plan. But it may not be the most efficient way to go about it. When you create a financial plan, you get a good deal of insight into your income and expenses. You can track and cut down your costs consciously. This automatically increases your savings in the long run.",
    financialBenefits2: "Most people assume that they would have to sacrifice their standard of living if their monthly bills and EMI repayments are to be addressed. On the contrary, with a good financial plan, you would not need to compromise your lifestyle. It is possible to achieve your goals while living in relative comfort.",
    financialBenefits3: "Creating an emergency fund is a critical aspect of financial planning. Here, you need to ensure that you have a fund that is equal to at least 6 months of your monthly salary. This way, you don’t have to worry about procuring funds in case of a family emergency or a job loss. The emergency fund can help you pay for varied expenses on time.",
    financialBenefits4: "With adequate funds at hand, you can cover your monthly expenses, invest for your future goals and splurge a little for yourself and your family, without worry. Financial planning helps you manage your money efficiently and enjoy peace of mind. Don’t worry if you have not yet reached this stage. If you are on the path of financial planning, the destination of financial peace is not very far away.",
    benefitsHeader1: "Increase your savings:",
    benefitsHeader2: "Enjoy a better savings of living:",
    benefitsHeader3: "Be prepared for emergencies:",
    benefitsHeader4: "Attain peace of mind:",
    mutualOverview1: "A mutual fund is a pool of money managed by a professional Fund Manager.",
    mutualOverview2: "It is a trust that collects money from a number of investors who share a common investment objective and invests the same in equities, bonds, money market instruments and/or other securities. And the income/gains generated from this collective investment is distributed proportionately amongst the investors after deducting applicable expenses and levies, by calculating a scheme’s “Net Asset Value” or NAV. Simply put, the money pooled in by a large number of investors is what makes up a Mutual Fund. ",
    mutualOverview3: "Next, let us understand what is “Net Asset Value” or NAV. Just like an equity share has a traded price, a mutual fund unit has Net Asset Value per Unit. The NAV is the combined market value of the shares, bonds and securities held by a fund on any particular day (as reduced by permitted expenses and charges). NAV per Unit represents the market value of all the Units in a mutual fund scheme on a given day, net of all expenses and liabilities plus income accrued, divided by the outstanding number of units in the scheme.",
    mutualOverview4: "Mutual funds are ideal for investors who either lack large sums for investment, or for those who neither have the inclination nor the time to research the market, yet want to grow their wealth. The money collected in mutual funds is invested by professional fund managers in line with the scheme’s stated objective. In return, the fund house charges a small fee which is deducted from the investment. The fees charged by mutual funds are regulated and are subject to certain limits specified by the Securities and Exchange Board of India (SEBI). ",
    mutualOverview5: "While investors of all categories can invest in the securities market on their own, a mutual fund is a better choice for the only reason that all benefits come in a package. ",
    mutualOverview6: "Mutual funds offer multiple product choices for investment across the financial spectrum. As investment goals vary – post-retirement expenses, money for children’s education or marriage, house purchase, etc. – the products required to achieve these goals vary too. The Indian mutual fund industry offers a plethora of schemes and caters to all types of investor needs. ",
    mutualOverview7: "Mutual funds offer an excellent avenue for retail investors to participate and benefit from the uptrend in capital markets. While investing in mutual funds can be beneficial, selecting the right fund can be challenging. Hence, investors should do proper due diligence of the fund and take into consideration the risk-return trade-off and time horizon or consult a professional investment adviser. Further, in order to reap maximum benefit from mutual fund investments, it is important for investors to diversify across different categories of funds such as equity, debt and gold. ",
    mutualType1: "An equity fund is a mutual fund scheme that invests predominantly in equity stocks.",
    mutualType2: "In the Indian context, as per current SEBI Mutual Fund Regulations, an equity mutual fund scheme must invest at least 65% of the scheme’s assets in equities and equity related instruments. As per current Income Tax rules, an ",
    mutualType21: "Equity Oriented Fund",

    mutualType22: "means a Mutual Fund Scheme where the investible funds are invested in equity shares in domestic companies to the extent of more than 65% of the total proceeds of such fund.",
    mutualType3: "An Equity Fund can be actively managed or passively managed. Index funds and ETFs are passively managed.",
    mutualType4: "Equity mutual funds are principally categorized according to company size, the investment style of the holdings in the portfolio and geography.",
    mutualType5: "A debt fund is a mutual fund scheme that invests in fixed income instruments, such as Corporate and Government Bonds, corporate debt securities, and money market instruments etc. that offer capital appreciation. Debt funds are also referred to as Income Funds or Bond Funds.",
    mutualType6: "Debt funds invest in either listed or unlisted debt instruments, such as Corporate and Government Bonds at a certain price and later sell them at a margin. The difference between the cost and sale price accounts for the appreciation or depreciation in the fund’s net asset value (NAV). Debt funds also receive periodic interest from the underlying debt instruments in which they invest. In terms of return, debt funds that earn regular interest from the fixed income instruments during the fund’s tenure are similar to bank fixed deposits that earn interest. This interest income gets added to a debt fund on a daily basis. If the interest payment is received, say, once every year, it is divided by 365 and the debt fund’s NAV goes up daily by this small amount. Thus, a debt scheme’s NAV also depends on the interest rates of its underlying assets and also on any upgrade or downgrade in the credit rating of its holdings.",
    mutualType7: "Debt funds invest in either listed or unlisted debt instruments, such as Corporate and Government Bonds at a certain price and later sell them at a margin. The difference between the cost and sale price accounts for the appreciation or depreciation in the fund’s net asset value (NAV). Debt funds also receive periodic interest from the underlying debt instruments in which they invest. In terms of return, debt funds that earn regular interest from the fixed income instruments during the fund’s tenure are similar to bank fixed deposits that earn interest. This interest income gets added to a debt fund on a daily basis. If the interest payment is received, say, once every year, it is divided by 365 and the debt fund’s NAV goes up daily by this small amount. Thus, a debt scheme’s NAV also depends on the interest rates of its underlying assets and also on any upgrade or downgrade in the credit rating of its holdings. ",
    mutualType8: "A balanced fund combines equity stock component, a bond component and sometimes a money market component in a single portfolio. Generally, these hybrid funds stick to a relatively fixed mix of stocks and bonds that reflects either a moderate, or higher equity, component, or conservative, or higher fixed-income, component orientation. These funds invest in a mix of equities and debt, giving the investor the best of both worlds. Balanced funds gain from a healthy dose of equities but the debt portion fortifies them against any downturn",
    mutualtypeHeader1: "Equity Funds:",
    mutualtypeHeader2: "Debt Funds:",
    mutualtypeHeader3: "Liquid Funds:",
    mutualtypeHeader4: "Balanced Funds:",
    mutualBenefits1: "Take some of the worries out of investing by allowing the mutual fund Managers do a little of the work for you. Mutual Funds can help lower investing risks & decisions. Mutual funds give your savings a chance to grow",
    mutualBenefits2: "Investing in mutual funds offers benefits and advantages, you will not get from trading individual stocks and bonds on your own.",
    mutualBenefits3: "One mutual fund can invest in hundreds of Individual stocks, sometimes even in thousands of securities at the same time. So, if any one security does poorly, the others are there to help offset that risk.",
    mutualBenefits4: "You don't have to keep track of every security your mutual fund owns. The fund is managed by experts who take care of that for you.",
    mutualBenefits5: "You can buy and sell mutual fund shares online or set up automatic investments and withdrawals through an Asset Management Company(AMC)",
    mutualBenefits6: "You end up paying one (hopefully low) expense ratio, instead of racking up the commissions you may pay when buying and selling individual stocks yourself. ",
    mutualbenefitsHeader1: "More Diversification, Less Risks:",
    mutualbenefitsHeader2: "Professional management:",
    mutualbenefitsHeader3: "Convenience:",
    mutualbenefitsHeader4: "Lower costs:",
    mutualEligibility1: "Indian resident adult individuals above the age of 18 either singly or jointly (not exceeding 3 people)",
    mutualEligibility2: "Minor through parent / lawful guardian",
    mutualEligibility3: "Non-resident Indians (NRIs)/ Persons of Indian Origin on a full repatriation basis (subject to RBI approval, if required) or on a non-repatriation basis.",
    mutualEligibility4: "Religious and charitable trusts (through trustees), and private trusts authorized to invest in Mutual Fund schemes under their trust deeds",
    mutualEligibility5: "Partnership Firms",
    mutualEligibility6: "Hindu Undivided Family (HUF) in the name of HUF or Karta",
    mutualEligibility7: "Banks (including Co-operative Banks and Regional Rural Banks) & Financial Institutions",
    mutualEligibility8: "Foreign Institutional Investors (FIIs) registered with SEBI on the basis of full repatriation basis (subject to RBI approval, if required)  ",
    mutualEligibility9: "Companies, bodies corporate, public sector undertakings, An association of persons or bodies of individuals and societies registered under the Societies Registration Act, 1860 (so long as the purchase of units is permitted under the respective constitutions)",
    mutualEligibility10: "Army, Air Force, Navy and other Para-military funds and eligible institutions",
    mutualEligibility11: "Scientific and Industrial Research Organizations",
    mutualEligibility12: "Provident / Pension / Gratuity and such other Funds as and when permitted to invest",
    mutualEligibility13: "International Multilateral Agencies approved by the Government of India / RBI",
    mutualEligibility14: "Trustees, AMC or Sponsor or their associates (if eligible and permitted under   prevailing laws), may subscribe to the Units under the Scheme.  ",
    mutualEligibility15: "Qualified Foreign Investors (QFIs)",
    mutualEligibility16: "Other individuals/institutions/corporate bodies, as approved by asset management companies, so long as they conform to SEBI regulations",
    mutualEligibility17: "Special Purpose Vehicles approved by an appropriate authority (subject to RBI approval)",
    mutualEligibility18: "Unincorporated bodies of persons as specified by asset management companies",
    mutualBrand1: "Aditya Birla Sun Life Mutual Fund",
    mutualBrand2: "Axis Mutual Fund",
    mutualBrand3: "Baroda Pioneer Mutual Fund",
    mutualBrand4: "Canara Robeco Mutual Fund",
    mutualBrand5: "DHFL Pramerica Mutual Fund",
    mutualBrand6: "DSP #000rock Mutual Fund",
    mutualBrand7: "Edelweiss Mutual Fund",
    mutualBrand8: "Franklin Templeton Mutual Fund",
    mutualBrand9: "HDFC Mutual Fund",
    mutualBrand10: "HSBC Mutual Fund",
    mutualBrand11: "ICICI Prudential Mutual Fund",
    mutualBrand12: "IDBI Mutual Fund",
    mutualBrand13: "IDFC Mutual Fund",
    mutualBrand14: "Invesco Mutual Fund",
    mutualBrand15: "JM Financial Mutual Fund",
    mutualBrand16: "Kotak Mahindra Mutual Fund",
    mutualBrand17: "L&T Mutual Fund",
    mutualBrand18: "LIC Mutual Fund",
    mutualBrand19: "Mirae Asset Mutual Fund",
    mutualBrand20: "Motilal Oswal Mutual Fund",
    mutualBrand21: "Reliance Mutual Fund",
    mutualBrand22: "SBI Mutual Fund",
    mutualBrand23: "Sundaram Mutual Fund",
    mutualBrand24: "Tata Mutual Fund",
    mutualBrand25: "UTI Mutual Fund",
    lifeOverview: "Life Insurance is defined as a contract between the policy holder and the insurance company, where the life insurance company pays a specific sum to the insured individual's family upon his death. The life insurance sum is paid in exchange for a specific amount of premium. In legal terms, life insurance is a contract between an insurance policy holder (insured) and an insurance company (insurer). Under this contract, the insurer promises to pay a pre-decided sum of money (also known as “Sum Assured” or “Cover Amount”) upon the death of the insured person or after a certain period.",
    lifeType1: "Term insurance:",
    lifeType11: "Term insurance is the most basic form of life insurance. They provide life cover with no savings/profits component. They are the most affordable form of life insurance as premiums are cheaper compared to other life insurance plans.",
    lifeType2: "Endowment plans:",
    lifeType21: "Endowment plans differ from term plans in one important aspect i.e. maturity benefit. Unlike term plans which pay out the sum assured, along with profits, only in case of an eventuality over the policy term, endowment plans pay out the sum assured under both scenarios – death and survival.",
    lifeType3: "Unit linked insurance plans (ULIP):",
    lifeType31: "Unit linked insurance plans (ULIP) is a variant of the traditional endowment plan. They pay out the sum assured (or the investment portfolio if it’s higher) on death/maturity. Since ULIPs invest in stock markets they are well-suited for individuals with an appetite for risk.",
    lifeType4: "Whole life policy:",
    lifeType41: "Whole life policy covers a policyholder over his life. The main feature of a whole life policy is that the validity of the policy is not defined so the individual enjoys the life cover throughout his life.",
    lifeType5: "Money back policy:",
    lifeType51: "Money back policy is a variant of the endowment plan. A money back policy gives periodic payments over the policy term. To that end, a portion of the sum assured is paid out at regular intervals. If the policy holder survives the term, he gets the balance sum assured.",
    lifeBenefits: "Insurance can prove advantageous in meeting several financial goals of the individual and his family. Here are some of the important ones: Financial cover against loss of life, which makes sure family can support itself in the absence of an individual on multiple financial goals like Child’s education, Child’s marriage, Buying a house, Pension or regular income post-retirement.",
    lifeEligibility1: "Basic eligibility for taking insurance for individual works on the basis of income capacity and health background.",
    lifeEligibility2: "Income Capacity:",
    lifeEligibility21: "Primarily insurance cover is given as against the individual’s income in order to safe guard the family in the absence of individual   ",
    lifeEligibility3: "Health Background:",
    lifeEligibility31: "Insurance policy is issued for a healthy individual at the time of issuance of policy, pre-existence of medical illness can be considerable depends on the nature and severity of the illness.  ",
    lifeBrand1: "Aegon Life Insurance Co. Ltd.",
    lifeBrand2: "Aviva Life Insurance Co. India Ltd.",
    lifeBrand3: "Bajaj Allianz Life Insurance Co. Ltd.",
    lifeBrand4: "Bharti AXA Life Insurance Co. Ltd.",
    lifeBrand5: "Birla Sun Life Insurance Co. Ltd.",
    lifeBrand6: "Canara HSBC Oriental Bank of Commerce Life Insurance Co. Ltd.",
    lifeBrand7: "DHFL Pramerica Life Insurance Co. Ltd.",
    lifeBrand8: "Edelweiss Tokio Life Insurance Co. Ltd",
    lifeBrand9: "Exide Life Insurance Co. Ltd.",
    lifeBrand10: "Future Generali India Life Insurance Co. Ltd.",
    lifeBrand11: "HDFC Standard Life Insurance Co. Ltd.",
    lifeBrand12: "ICICI Prudential Life Insurance Co. Ltd.",
    lifeBrand13: "IDBI Federal Life Insurance Co. Ltd.",
    lifeBrand14: "IndiaFirst Life Insurance Co. Ltd",
    lifeBrand15: "Kotak Mahindra Old Mutual Life Insurance Ltd.",
    lifeBrand16: "Life Insurance Corporation of India",
    lifeBrand17: "Max Life Insurance Co. Ltd.",
    lifeBrand18: "PNB MetLife India Insurance Co. Ltd.",
    lifeBrand19: "Reliance Life Insurance Co. Ltd.",
    lifeBrand20: "Sahara India Life Insurance Co. Ltd.",
    lifeBrand21: "SBI Life Insurance Co. Ltd.",
    lifeBrand22: "Shriram Life Insurance Co. Ltd.",
    lifeBrand23: "Star Union Dai-Ichi Life Insurance Co. Ltd.",
    lifeBrand24: "Tata AIA Life Insurance Co. Ltd.",
    planningHeader1: "Planning",
    planningContent1: "Personal financials are better managed by planning, recording and projecting your financial futures. We at Bloomkite created multiple tools in the planning, investments and loan section.  These tools will help you have a customized plan for ready references. You can share these details to qualified financial advisors at Bloomkite for taking advice. Rest assured your data is fully secured and safe with us and you will be sharing your own data on a two factor authentication basis.",
    planningContent2: "Goal Planning: ",
    planningContent21: "Everyone has needs and aspirations. The needs or aspirations are a good starting point, but in order to plan, these need to be converted into financial goals. The financial goals must be defined in terms of time horizon and the amount of money required in achieving the goal.",
    planningContent3: "Financials:",
    planningContent31: "Budgeting of income and expenses is an important exercise in managing personal finance. Planned expenditure will lead to efficient cash flow management and thus will result in a surplus. Recording of expenditures and income is more so important for pursuing financial goals.",
    planningContent4: "Risk Profile: ",
    planningContent41: "Risk profiling is an evaluation questionnaire which will give details about a person’s willingness and ability to take risk while making investments. Risk Profile is important for determining a proper asset allocation for portfolio investments.",
    planningContent5: "Investments:",
    planningContent51: "Time value of money is a centric point in which the entire world of investments works around. Future value, current value, percentage of growth and Tenure required are the basic arithmetic that will support the right investment decision.",
    planningContent6: "Home Loans:",
    planningContent61: "Considered to be the most productive loan generally applied for a long tenure. Managing the tenure to the shortest possible period will result in reduced interest outflow. Reduction in tenure is achieved by making partial payments, Increasing EMI, and reducing the interest rate.",
    planningContent7: "Create your account now to make use of the best available financial tools to manage your finance for any of the options like Goals, Budgeting, Risk Profile, Investments and Home Loans.",
    howitworksAdvisor1: "Profile Section:",
    howitworksAdvisor11: " Creating profile involves providing information about person, education, experience, product and services. Further advisors can add images and videos to promote their profile among the prospective clients. Fully completed profile is a kind of micro website for an advisor which can be shared through link and also downloadable. Once profile information is fully updated to the satisfactory level, the advisor should request for publication. Bloomkite will do cross check on your profile information and approve the same. Approved profiles will get promoted in Bloomkite website in multiple pages like search database, matching clients, matching products and matching brands. Hence providing maximum information will help in promoting advisor profile to the maximum extent. ",
    howitworksAdvisor2: "Planning Section:",
    howitworksAdvisor21: " Advisor can create planning sheets which can be prepared for client financial goals, budgeting, Investment Plans, Risk Profile and Home Loans. Client specific planning sheets will be stored under client name and can be modified any time later. Advisors can add any number of planning sheets and the same can be shared and downloadable. Advisor can make his advice on the respective planning sheet and the same can be referred for future references. Prospective clients registered under Investor profile can seek advice from advisors by sharing their planning sheet. Advising registered investors in Bloomkite will create an opportunity for advisors to onboard new clients for their products and services offerings.  ",
    howitworksAdvisor3: "Forum:",
    howitworksAdvisor31: " Financial advice is all about transformation of knowledge; successful advisors will always educate their clients so that financial advice becomes an intellectual transaction. Best way to share knowledge is to post articles for the benefit of others. Article postings will convey a lot about advisors to prospective clients. It also opens up client interaction under the areas of expertise. Advisor can choose to post articles to open forums or to followers, which gives a lot of control on sharing of knowledge.       ",
    howitworksAdvisor4: "Public Profile:",
    howitworksAdvisor41: " Advisor public profile is a kind of micro website about the respective advisor. Approved advisor profiles will be featured under search database and matching profiles. Indeed it is in the hands of the advisor to create a better profile with sufficient information. Multimedia files like images and videos can communicate a lot about an advisor. Having right images to relate advisor profiles or to promote specific products will be more appropriate. Advisor should have a video profile to convey his services to prospective clients. Public profile page will have information about the advisor through text, images and video format. Public profile page will also have requests for followers and chat facility. ",
    howitworksAdvisor5: "Client Interaction:",
    howitworksAdvisor51: " Engaging with prospective clients is an ultimate idea for making meaningful conversation. Prospective clients can start a chat conversation with an advisor from his public profile page directly. There are multiple ways it leads to conversation other than profile page like posting articles, matching advisor profile, matching product profile, matching brand profile, etc. Advisors should make use of every possible interaction to a meaningful conversation.   ",
    howitworksAdvisor6: "Team Management:",
    howitworksAdvisor61: " Corporate advisors can create company profiles and employee profiles as well. Corporate will be able to manage their employees' activities right from creating profile, planning for clients, article postings and client interaction. Corporate with few employees will create good synergy for doing joint advice and boost confidence among clients . ",
    howitworksInvestor1: "Investors can create a simple profile with basic information like name, location and contact details. ",
    howitworksInvestor2: "Investors can update the planning sheet at their convenience. Investors can also seek advisors help in getting advised on their respective planning sheet.   ",
    howitworksInvestor3: "Investors can explore advisors; product information and also can get financial advice by qualified advisors for their financial queries.  ",
    howitworksInvestor4: "Investors can read articles under the forum section to have updates on financial topics and choose the right advisor for their related financial advice. ",
    howitworksInvestor5: "Investors can interact with advisors in multiple ways like chat facility, reaching out on contact details, following the advisor, commenting on articles for clarifications.  ",
    howitworksInvestor6: "In simple investors can expect financial planning and advisory services from financial advisors through Bloomkite platform.",
    userState: "Choose State",
    userCity: "Choose City",
    userPincode: "Choose Pincode",
    userSearch: "Search:",
    productName: "Choose Product Name",
    productService: "Choose Service Name",
    productBrand: "Choose Brand Name",
    productPlan: "Choose Plan Name",
    productHeader: "Product",
    planningHeader: "Planning",
    exploreHeader: "Experts",
    howitworksHeader: "How It Works",
    asAdvisor: "As Advisor",
    asCompany: "As Company",
    asInvestor: "As Investor",
    loggingIn: "Login",
    whyusHeader: "Why Us",
    whyus1: "We want you to upskill and cultivate on Managing Finance...Be it Beginner or an Expert!",
    whyus2: "“Money makes Money”",
    whyus3: "Money is associated with lots of confidence, freedom, power and achievements. It requires some kind of blooming efforts jointly with family and professionals at the beginning. Sustainable cash flows are required at every stage of the family life cycle for happy living. Once financial status and wealth creation reaches the threshold level after which multiplying of money needs less effort only. We get a sense of achievement once we become financially independent.",
    whyus4: "Many people earn more money but only a few succeed in managing the money, which requires a professional approach to our relationship with money. We believe experts like Financial Advisor plays a major role in managing money. Expert financial advice helps individuals to achieve financial freedom sooner than later. A professional financial advisor helps individuals take the right financial decision at the right point of time.",
    whyus5: "In this background, we have started Bloomkite to make individuals aware of the financial subject and get connected with a professional financial advisor. We request individuals to consider Bloomkite before taking the financial decision. Ultimately we want individuals to achieve financial freedom sooner than later...Happy Financial Life...",
    whyus6: "Sundar Kumarasamy",
    whyus7: "CEO - Bloomkite",
    disclaimerHeader: "Disclaimer:",
    disclaimerContent1: "Bloomkite.com is a product of Sowise Technologies Private Ltd is trying to provide and captures information related to personal finance with the intention to help users make informed financial decision, In the process of connecting financial distributors to financial consumer there can be some kind of information exchanged on bloomkite.com between financial distributor and other users registered with bloomkite.com. Any such exchange of information is of incidental nature and should not be treated as Investment Advice, Mutual Fund / Stocks Recommendation, Insurance solicitation, Financial Planning and Loan selling. ",
    disclaimerContent2: "www.bloomkite.com or partners associated with bloomkite.com does not provide any trading or investment advice on bloomkite website and other web-based services (collectively, the “Website Services) and shall not be responsible for any loss arising from any investment based on any general information provided by bloomkite or partners associated. Bloomkite does not warrant that the information is accurate, reliable or complete or that the supply will be without interruptions. Any third party information provided through does not reflect the views of Bloomkite.",
    disclaimerContent3: "The content of the Website Services provided by Bloomkite is only intended to provide you with general information and is neither an offer to sell nor a solicitation of an offer to purchase any security and may not be relied upon for investment purposes. Any commentaries, articles, daily news items, public and/or private chat publications, stock analysis and/or other information contained in the Website Services should not be considered investment advice.",
    calculatorHeader: "Plans",

    equilyOverview: "Equity investment is a financial transaction where certain number of shares of a given company or fund are bought, entitling the owner to be compensated according to his ownership percentage. Returns on Equity investment will be in the form of either capital gains or dividends. It is an operation where an individual or company invest money into a private or public company to become a shareholder.",
    fixedOverview: "Fixed income broadly refers to those types of investment security that pay investors fixed interest or dividend payments until its maturity date. At maturity, investors are repaid the principal amount they had invested. Government and corporate bonds are the most common types of fixed-income products. Unlike equities that may pay no cash flows to investors, or variable-income securities, where can payments change based on some underlying measure—such as short-term interest rates—the payments of a fixed-income security are known in advance.",

    healthOverview: "To be financially stable is everyone’s dream. However, with rising medical costs, treatment for illnesses can easily eat into your savings. Arranging funds during a medical emergency can also be a daunting task. A health insurance policy can protect you from the financial strain caused due to a medical emergency.",
    equityHead1: "Individual Stocks:",
    equityType1: "Investors can park their funds into one or more stocks depending on their preference. This form of equity investment can be ventured into independently and complete control over own funds is retained. No involvement from any fund managers or analysts is required. The trade can be executed by the investor himself. The decision regarding the stocks to pick may be at the investor’s own discretion. Alternatively, guidance can also be sought from various sources such as trade shows and expert recommendations",
    equityHead2: "Equity Funds:",
    equityType2: "Equity funds are a variation of mutual funds whereby the majority of the funds are invested into stocks and shares of companies. These funds are basically a pool of several equity stocks. They are aggregated and units of the fund are then sold to the investors. Consequently, an investor is able to enjoy the benefits of diversification and cover a wider base of equity investments. This would not be possible in an individual capacity by the investor.",
    equityHead3: "Private Equity Investments:",
    equityType3: "They represent investing in stocks of companies not listed on the exchange. They are generally not liquid and involve a huge ticket size. For this reason, only high net worth individuals and institutional investors can afford to invest in them. Private equity investments are resorted to at the inception or expansionary phase of a venture and entail high return on investment",
    equityStrong1: "Diversification:",
    equityBenefits1: "The equity investments can be diversified across various sectors, cap, geographies and even the phase of business cycles. The investor is thus protected against the consequences of “putting all eggs in one basket”. Turbulence in any specific stocks or sectors is unable to adversely impact the value of the portfolio as a whole.",
    equityStrong2: "Risk Adjusted:",
    equityBenefits2: "A wide arena of mutual and equity funds have emerged lately. The sheer abundance of these funds enables the investor to choose a fund which exactly caters to his investment preferences. There is something for everyone in today’s market. Conservative to aggressive equity investment funds are available rampantly. Equity investments were earlier synonymous with risk and uncertainty. With the advent of portfolio funds that is no longer the case. Funds offset risky equity investments with cash and bond positions to offer a relatively secure product to the investor.",
    equityStrong3: "Liquidity: ",
    equityBenefits3: "Though not always true for private equity investments, liquidity is a sure shot benefit for listed and public stocks. There is a ready market available for shares of listed companies. The volume and number of transactions are always large enough to assure the investor of a ready sell whenever he intends to. Cashing out and squaring position at any time is possible. Therefore, equity investments serve as a lucrative means of investment for investors with a not so long horizon.",
    fixedHead1: "Bank Deposits:",
    fixedType1: "Fixed income vehicle offered by Banks with maturities of less than five years. The rate is higher than a typical saving account, and fixed deposits are under the preview of RBI.",
    fixedHead2: "Company Deposits:",
    fixedType2: "Fixed income vehicle offered by Non-Banking Financial Institutions with maturities of less than five years. The rate is higher than a typical saving account, and bank fixed deposits.",
    fixedHead3: "Corporate bonds:",
    fixedType3: "Comes in various types, and the price and interest rate offered largely depends on the company’s financial stability and its creditworthiness. Bonds with higher credit ratings typically pay lower coupon rates",
    fixedHead4: "Fixed-income mutual funds:",
    fixedType4: "Invest in various bonds and debt instruments. These funds allow the investor to have an income stream with the professional management of the portfolio. However, they will pay a fee for the convenience.",
    fixedBenefits1: "Fixed income is a class of assets and securities that pay out a set level of cash flows to investors, typically in the form of fixed interest or dividends.",
    fixedBenefits2: "At maturity for many fixed income securities, investors are repaid the principal amount they had invested in addition to the interest they have received.",
    fixedBenefits3: "Government and corporate bonds are the most common types of fixed-income products.",
    fixedBenefits4: "In the event of a company's bankruptcy, fixed-income investors are often paid before common stockholders",
    loanOverview1: "Personal loans are structured credit arrangements amount, and how many payments are required to repay the loan. Repayment terms can vary, and interest rates are either fixed, where the rate stays the same during the term, or variable, where the rate fluctuates with the market.",
    loanOverview2: "Lenders fix interest rates based on several factors. Largely influenced by RBI’s Repo rate, inflation levels, the type of lending product you want, the amount you wish to borrow, and the credit profile of the borrowers.",
    loanOverview3: "Generally, rates are lower when loans are secured with some form of collateral like home, car, etc., as the lender has less risk to assume. Your credit rating will also be considered. A higher credit score indicates that you are a lower credit risk, and will likely entitle you to a better rate.",
    loanOverview4: " Because the features of a loan are as varied as the reasons for borrowing, it is important that you get the right loan for the right purpose. Your loan advisor can help you determine the best product for your personal situation.",
    loanHead1: "Personal Loan:",
    loanType1: "Personal loans are provided to meet the personal needs of the borrower. You can use the money from this type of loan in any way you see fit. You can pay off your previous debts, buy some expensive accessories for yourself, and plan a great trip with your family. It’s up to you how to use the money. The interest rates for this type of loan are on the higher side compared to the other types of loans.",
    loanHead2: "Home Loan:",
    loanType2: "Everybody dreams of owning their own house. However, buying a house needs a lot of money and it is not always possible to have that much money at once. Banks now offer home loans that can assist you in purchasing a property. A home loan can be of different types such as: Loan for constructing a house / flat, Loan for repairing and remodelling your existing home, Loan for purchasing a land.",
    loanHead3: "Gold Loan:",
    loanType3: "Among all the types of loans available in India, the fastest and easiest one to get is the gold loan. This type of loan was very popular back in the days when the rates of gold were rising exponentially. Gold companies are facing losses due to falling rates of gold in the recent times.",
    loanHead4: "Vehicle Loan:",
    loanType4: "Vehicle loans help you fulfil your dream of owning a car or bike. Almost all banks provide this type of loan. It a secured loan means if the borrower doesn’t pay the instalments in time, the bank has the right to take back the vehicle.",
    loanHead5: "Loan against Mutual Funds or Shares:",
    loanType5: "Generally, people offer their mutual fund investment or shares as a collateral for their loan application. The banks give out loans of an amount lesser than the total valuation of the shares or mutual fund investment. The amount is lesser because the bank can then charge rate of interest if the borrower is unable to repay the amount.",
    loanBenefits: "A loan reduces the burden of paying cash outright for major purchases, and allows you to spread the cost out over time. A personal loan, by definition, is an extension of credit by a lender to a borrower, where the borrower agrees to pay back the lender at a predetermined time, with interest. Anyone faced with a large purchase - a home, a car, home renovations or education costs - will likely need to consider borrowing money through a personal loan.",
    loanEligibility1: "Most banks have strict eligibility criteria which depends on applicants age, location, salary, company of employment, marital status, credit score etc. The ideal customer for the banks is a person with a credit score of at least 750 whom they consider extremely low default risk.",
    loanEligibility2: " Eligibility criteria and the factors that affect your loan application to make sure that your loan doesn’t get rejected as each time your loan is rejected it will adversely affect your credit score. If your credit score reduces a lot, it will become very difficult to get a loan or the loan will be of very high interest rate.",
    loanEligibility3: "The lender will also fix your loan maximum and minimum based on your repayment capacity calculated based on your disposable income. It is best to know all these factors before applying for a loan so that your application is not rejected, and you get the best loan offer possible.",
    healthHead1: "Individual Health Insurance Plan:",
    healthType1: "Individual Health Insurance Plan is a type of health insurance that covers health expenses of an insured individual. These policies pay for surgical and hospitalisation expenses of an insured individual till the cover limit is reached. The premium for an individual plan is decided on the basis of medical history and the age of the individual buying the plan.",
    healthHead2: "Family Floater Health Insurance Plan:",
    healthType2: "If a person wants to buy health insurance for his entire family (spouse, children and parents) in a single plan, then he should go for a Family Floater Policy. Any family member covered under the policy can claim in case of hospitalisation and surgical expenses. Like Individual Health Insurance Plan one has to pay a premium for family floater policy. The premium for family floater policy is determined based on the age of the eldest member under the coverage of the policy.",
    healthHead3: "Group Health Cover:",
    healthType3: "Group Health Insurance plans are bought by an employer for his employees. The premium in group insurance is lower than individual health insurance policy. Group health plans are usually standardised in nature and offer the same benefits to all employees.",
    healthHead4: "Senior Citizen Health Insurance:",
    healthType4: "At old age, health issues arise that involve expensive treatments. In order to meet such high medical cost, insurance companies have designed special health insurance plans for senior citizens. These plans provide cover to anyone from the age of 65 and above. Generally, the premium is higher in the case of senior citizen health insurance plan as compared to other policies.",
    healthHead5: "Critical Illness Health Cover:",
    healthType5: "Critical Illness Policy covers the expenses involved in treating the life-threatening diseases like a tumour, permanent paralysis etc. These policies usually pay a lump sum amount to insured person on the diagnosis of serious diseases covered in the policy document. Unlike other policies, Individual Health Insurance and Family Floater Policy, hospitalisation is not required, only the diagnosis of the disease is enough to claim the benefits.",
    healthBenefits1: " Having health insurance in the present time is of utmost importance as it can financially protect you against the unavoidable expenses. This way, your savings also remain protected.",
    healthBenefitshead1: "Free health check-up:",
    healthBenefits2: "Health insurance understands that health is wealth; therefore, it needs consistent health monitoring. As a policyholder, you are eligible for a free preventive health check-up after an every 4 to 5 claim-free year. Some insurers also offer cashless treatments at their network hospital.",
    healthBenefitshead2: "Tax benefits:",
    healthBenefits3: "You can avail tax benefits under Section 80D of the Income Tax Act. As part of the law, you can avail tax benefit for the expenses incurred on the preventive health check-up of parents above 60 years. Below is the table which shows the tax deductions for various health cover:",

    generalOverview: "Insurance contracts that do not come under the ambit of life insurance are called general insurance. The different forms of general insurance are fire, marine, motor, accident and other miscellaneous non-life insurance.",
    generalOverview1: "The tangible assets are susceptible to damages and a need to protect the economic value of the assets is needed. For this purpose, general insurance products are bought as they provide protection against unforeseeable contingencies like damage and loss of the asset. Like life insurance, general insurance products come at a price in the form of premium.",
    generalHead1: "Travel Insurance:",
    generalHead2: "Motor Insurance:",
    generalHead3: "Home Insurance:",
    generalType1: "covers your financial liability, if any, when you travel within or beyond the Indian boundaries. The financial liability may arise due to medical or non-medical emergencies.",
    generalType2: "The duration of the travel for one time can be 180 days at the maximum. The policyholder can take more than one trip in a year.",
    generalType3: "Policy is mandatory to be able to drive legally in India. Broadly there are two types a) Third-Party Liability b) Comprehensive Package Policy.",
    generalType4: "A Third-Party Policy covers for losses faced in a situation where your vehicle damages any third-party such as a public property, person or third-party vehicle. The same is the minimum requirement to be able to drive legally in India, as stated by the Motor Vehicles Act.",
    generalType5: "A Comprehensive Package Policy covers both third-party damages and liabilities and damages/losses caused to you and your own vehicle. The losses may arise due to an accident, theft, fire, natural calamities, and others.",
    generalType6: "You build your home with your toil and hard earned money. Everything you buy is a priceless possession for you and hence it needs to be protected. A Home Insurance Policy protects your valuable and other assets. It is a comprehensive package policy that covers all valuables.",



};

export { homeMessage };