const planningMessage = {
    planningTitle: 'PLANNING',
    planningGoals: 'Goal',
    goalInfo: 'Create Financial Goals and review on periodic basis for progress',
    financialName: 'Financial Planning',
    financialInfo: 'Failing plan is planning to fail, Make your financial plan right',
    riskName: 'Other Planning',
    riskInfo: 'Investment decision is all about making optimum returns not high returns',
    homeName: 'Loan Planning',
    homeInfo: 'People need more than what they earn how much to leverage and how to manage',
    investment: 'Investment',
    investmentInfo: 'Investment decision is all about making optimum returns not high returns',
    planningAdd: 'ADD PLAN',
    planningSelect: 'Select',
    planningSelf: 'Self',

    planningTableName: 'Name',
    planningTableInvName: 'Investor Name',
    planningTableEmployeeName: 'Employee Name',
    planningTableRef: 'Ref ID',
    planningTableAge: 'Age',
    planningTableTitle: 'Planning',
    planningTableAction: 'Actions',
    planningChat: 'Share',
    startCreating: 'Start Creating',
    loremInfo: ' Lorum ipsom is the simple dummy text for web and mobile to design check.',
    shareTerms: ' Your contacts will be shared to the following advisor',

    /*edit and add planning */

    plan: ' PLAN',
    name: 'Name',
    age: 'Age',
    selectPlan: 'SELECT PLANS',
    goals: 'Goal',
    financial: 'Financial',
    investments: 'Investment',
    homeLoan: 'Home Loan',
    loan: 'Home Loan',
    familyTitle: 'FAMILY DEPENDENCIES',
    spouse: 'Spouse',
    childA: 'Child 1',
    childB: 'Child 2',
    childC: 'Child 3',
    father: 'Father',
    mother: 'Mother',
    grandParent: 'Grand Parent',
    sibilings: 'Sibilings',
    inlaws: 'In-laws',
    others: 'Others',
    save: 'Save',

    /*planning list leftside-bar && planning header*/

    planningList: 'Planning List',
    edit: 'Edit',
    cancel: 'Cancel',
    headerSave: 'Save',
    share: ' Share',
    post: ' Post',

    goal: 'Goal',
    finance: 'Finance',
    cashflow: 'Cashflow',
    networth: 'Networth',
    priorities: 'Priorities',
    insurance: 'Insurance',
    riskprofile: 'Risk Profile',
    riskProfile: 'Risk Profile',
    futureValue: 'Future Value',
    targetValue: 'Target Value',
    rateFinder: 'Rate Finder',
    tenureFinder: 'Tenure Finder',
    emiCalculator: 'EMI Calculator',
    emiCapacity: 'EMI Capacity',
    partialPayments: 'Partial Payments',
    changeInEmi: 'Change in EMI',
    changeInInterest: 'Change in Interest',

    /* My goal */

    saveGoal: 'Saved Goals',
    viewGoal: 'View Goals',
    noSaveGoal: 'No saved goals!',
    futureCostGoal: 'Future Cost of Goal',
    futureValueAccumulations: 'Future Value of Accumulations',
    targetCorpus: 'Target Corpus',
    monthlyInvestments: 'Required Monthly Investments',
    yearlyInvestments: 'Required Yearly Investments',

    /* Finance */
    viewFinance: 'View Finance',
    cashFlowSummary: 'Cash Flow Summary',
    expenses: 'Expenses',
    monthly: 'Monthly',
    yearly: 'Yearly',
    recurring: 'Recurring',
    nonRecurring: 'Non-Recurring',
    income: 'Income',
    cashFlowList: 'Name of the list',
    budgetAmount: 'Budget Amount',
    actualAmount: 'Amount',
    netCashFlow: 'Net Cash Flow',

    networthSummary: 'Networth Summary',
    currentAssetsInHand: 'Current Assets in Hand',
    currentOutStandingLiabilities: 'Current Out Standing Liabilities',

    investmentRelated: 'Investment Related',
    urgency: 'Urgency',
    prioritiesSelect: 'Select',
    high: 'High',
    medium: 'Medium',
    low: 'Low',
    topPriorities: 'Top priorities',

    insuranceCoverage: 'Insurance Coverage Requirement',
    value: 'Value',
    insuranceSelect: 'Select',
    stable: 'STABLE',
    flunctuating: 'FLUCTUATING',
    predictble: 'PREDICTABLE',
    unpredictble: 'UNPREDICTABLE',
    additionalInsurance: 'Additional Insurance Requirement',

    /* Risk Profile */

    getStarted: 'GET STARTED',
    yourRiskProfile: 'Your Risk Profile',
    suggestedPortfolioAllocation: 'SuggestedPortfolioAllocation',
    equityInvestments: 'Equity Investments',
    debtBondsInvestments: 'Debt / Bonds Investments',
    cashEquivalent: 'Cash / Cash Equivalent',
    riskProfileInfo:
        "A risk profle is an evaluation of anindividual's willingness and ability to take risks. A risk profile is important for determining a proper investment asset allocationfor a portfolio.  Advisor use a risk profile as a wayto mitigate potential risks andthreats",

    /* Investment */
    viewInvestment: 'View Investments',
    totalPayment: 'Total Payment',
    investmentAmount: 'Investment amount required today',
    rateOfInterest: 'Required rate of interest to reach future Value',
    tentureToAchieve: ' Required tenure to achieve future Value',

    /*Loan */
    viewLoan: 'View Loans',
    loanStartDate: 'Loan Start Date',
    partialPaymentDate: 'Partial Payment Date',
    partialPaymentAmount: 'Partial Payment Amount',
    calculate: 'Calculate',

    emiStartDate: 'EMI Start Date',
    currentEmi: 'Current EMI',
    emiIncreaseDate: 'EMI Increase Date',
    additionalemi: 'Additional EMI',

    currentInterestStartDate: 'Current Interest Start Date',
    currentInterestRate: 'Current Interest Rate',
    revisedIntereststartDate: 'Revised Interest start Date',
    revisedInterestrate: 'Revised Interest rate',

    tableYear: 'Year',
    tablePrincipal: 'Principal',
    tableInterest: 'Interest',
    tableClosing: 'Closing',
    tableOpening: 'Opening',
    tableOutStanding: 'Outstanding Loan Amount',

    emiCapcity: 'EMI Capacity',
    currentAge: 'Current Age',
    retirementAge: 'Retirement Age',
    netFamilyIncome: 'Net family Income',
    emiIncludingSpouse: 'Existing EMI including spouse',
    houseExpenses: 'House hold Expenses',
    additionalIncome: 'Additional Income to considered (Rental Income and Tax Adjustments)'
};

export { planningMessage };
