const toastrMessage = {
    emptyError: 'Please fill the empty fields',
    emptyEducation: 'Please fill up education completely',
    yearError: 'Start year should be less than end year',
    emptyExperience: 'Please fill up experience completely',
    emptyAward: 'Please fill up awards completely',
    emptyCertificate: 'Please fill up certificate completely',
    emptyBrand: 'Please fill up brands completely',
    emptyProduct: 'Please fill up products completely',
    nameError: 'Please enter valid name',
    panError: 'Please enter valid PAN',
    phoneNumberError: 'Please enter valid phone number',
    emailError: 'Please enter valid email',
    passwordError: 'Please enter valid password',
    confirmPasswordError: 'Please enter same as password',
    emptyTerms: 'Please check the terms and conditions',
    emptyConfirmPassword: 'Please enter same as password',
    emptyPassword: 'Please enter valid password',
    emptyMail: 'Please enter valid email',
    emptyPhoneNumber: 'Please enter valid phone number',
    emptyPan: 'Please enter valid PAN',
    emptyName: 'Please enter valid name',
    emptyAll: 'Please enter all fields',
    emptyGender: 'Please enter gender',
    designationError: 'Please enter valid designation',
    emptyPincode: 'Please enter vaild pincode',

    advisorSuccessId: 'Advisor ID fetched Successfully',
    advisorSuccessList: 'Advisor List fetched Successfully',
    brandSuccessList: 'Brand List fetched Successfully',
    categorySuccessList: 'Category List fetched Successfully',
    categoryTypeSuccessList: 'Category Type List fetched Successfully',
    forumCategorySuccessList: 'Forum Category List fetched Successfully',
    forumStatusSuccessList: 'Forum Status List fetched Successfully',
    forumSubCategorySuccessList: 'Forum Sub Category List fetched Successfully',
    goalServedSuccessList: 'Goals Served List fetched Successfully',
    licenseSuccessList: 'License List fetched Successfully',
    partyStatusSuccessList: 'Party Status List fetched Successfully',
    productSuccessList: 'Product List fetched Successfully',
    allServiceSuccessList: 'All Service And Brand fetched Successfully',
    renumerationSuccessList: 'Renumeration List fetched Successfully',
    questionaireSuccessList: 'Risk Questionaire List fetched Successfully',
    roleSuccessList: 'Role List fetched Successfully',
    serviceSuccessList: 'Service List fetched Successfully',
    skillSuccessList: 'Specialised Skills fetched Successfully',
    allStateSuccessList: 'All State City Pincode fetched Successfully',
    brandBankSuccessList: 'Advisor Brand Rank By Advisor Id fetched Successfully',
    accountSuccessList: 'Account List fetched Successfully',
    accountTypeSuccessList: 'Account Type List fetched Successfully',
    cashFlowSuccessList: 'Cash Flow Item List fetched Successfully',
    cashFlowItemSuccessList: 'Cash Flow Item Type List fetched Successfully',
    prioritySuccessList: 'Priority Item List fetched Successfully',
    riskPortfolioSuccessList: 'Risk Portfolio List fetched Successfully',
    urgencySuccessList: 'Urgency List fetched Successfully',

    personalInfoError: 'Something went wrong while updating Personal Information. Please try again',
    productError: 'Something went wrong while updating product Information. Please try again',
    professionalError: 'Something went wrong while updating Professional Information. Please try again',
    changePasswordError: 'Something went wrong while updating change password. Please try again',
    invInterestError: 'Something went wrong while updating addAInvInterest. Please try again',
    advPersonalInfoError: 'Something went wrong while updating addAdvPersonalInfo. Please try again',
    fetchByInvestorId: 'Something went wrong while updating fetchByInvestorId. Please try again',
    modifyInvestor: 'Something went wrong While updating personal information. Please try again',
    modifyInvInterest: 'Something went wrong While adding area of investor interest. Please try again',
    deleteInvestor: 'Something went wrong while updating deleteInvestor. Please try again',
    deleteInvInterest: 'Something went wrong while updating deleteInvInterest. Please try again',
    uploadFileError: 'Please upload mentioned size or format of the image',
    addKeyPeopleError: 'while adding keypeople',

    financialPlanningError: 'Something went wrong while updating fetchFinancialPlanning. Please try again',
    loanPlanningError: 'Something went wrong while updating fetchLoanPlanning. Please try again',
    investmentPlanningError: 'Something went wrong while updating fetchInvestmentPlanning. Please try again',
    riskPlanningError: 'Something went wrong while updating fetchRiskPlanning. Please try again',
    planByRefError: 'Something went wrong while updating fetchPlanByReference. Please try again',
    addPlanError: 'Something went wrong while updating addPlan. Please try again',
    modifyPlanError: 'Something went wrong while updating modifyPlan. Please try again',
    deletePlan: 'Something went wrong while updating deletePlan. Please try again',
    calculateGoal: 'Something went wrong while updating calculateGoal. Please try again',
    calculateCashflow: 'Something went wrong while updating calculateCashflow. Please try again',
    calculateNetworth: 'Something went wrong while updating calculateNetworth. Please try again',
    calculatePriorities: 'Something went wrong while updating calculatePriorities. Please try again',
    calculateInsurance: 'Something went wrong while updating calculateInsurance. Please try again',
    calculateRiskProfile: 'Something went wrong while updating calculateRiskProfile. Please try again',

    createArticleError: 'Something went wrong while updating createArticlePost. Please try again',
    createArticleCommentError: 'Something went wrong while updating createArticlePostComment. Please try again',
    articleCommentError: 'Something went wrong while updating fetchArticleComment. Please try again',
    articleListByPartyError: 'Something went wrong while updating fetchArticleListByPartyId. Please try again',
    articlePostByArticleError: 'Something went wrong while updating fetchArticlePostByArticle. Please try again',
    createArticleVoteError: 'Something went wrong while updating createArticleVote. Please try again',
    changeArticleStatusError: 'Something went wrong while updating changeArticleStatus. Please try again',
    articlePostError: 'Something went wrong while updating fetchArticlePost. Please try again',
    inApprovedOrderError: 'Something went wrong while updating fetchAllArticleInApprovedOrder. Please try again',
    allForumCategoryError: 'Something went wrong while updating fetchAllForumCategory. Please try again',
    recentArticlePostListError: 'Something went wrong while updating fetchRecentArticlePostList. Please try again',
    recentApprovedArticleError: 'Something went wrong while updating fetchRecentApprovedArticle. Please try again',
    moderateArticlePostError: 'Something went wrong while updating moderateArticlePost. Please try again',
    moderateArticleCommentError: 'Something went wrong while updating moderateArticlePostComment. Please try again',
    deleteArticleError: 'Something went wrong while updating deleteArticle. Please try again',
    deleteArticleCommentError: 'Something went wrong while updating deleteArticleComment. Please try again',
    addArticleToFavoriteError: 'Something went wrong while adding article to favorite. Please try again',

    // signupSuccess: "Activation email send to your registered email",
    teamSignupSuccess: 'Team member added Successfully',
    keySignupSuccess: 'Keypeople added Successfully',
    loginSuccess: 'Logged Successfully',
    loginError: 'Please login with valid credentials',
    loginErrorFound: 'Error occured: ',
    signupError: 'Error Occured while Signup: ',
    expireError: 'Your session has been expired. Please login again',

    publishAdvisorError: 'Something went wrong While publishing the advisor. Please try again',
    publishAdvisorSuccess: 'Published Successfully',
    // teamDeactivate:"By deactivating your team member may result in deleting their planning list also. Deactivation can't be restored or recovered. Are you sure to remove your team member ?"

    somethingError: 'Something went wrong!'
};

export { toastrMessage };
