export const advisorSelector = (state) => ({
    loggedDetails: state.loginReducer,
    signedDetails: state.signinReducer,
    appState: state.appStateReducer,
    advisorDetails: state.advisorReducer.advisorDetails,
    brandList: state.advisorReducer.brandList,
    categoryList: state.advisorReducer.categoryList,
    categoryTypeList: state.advisorReducer.categoryTypeList,
    forumCategoryList: state.advisorReducer.forumCategoryList,
    forumStatusList: state.advisorReducer.forumStatusList,
    forumSubCategoryList: state.advisorReducer.forumSubCategoryList,
    licenseList: state.advisorReducer.licenseList,
    partyStatusList: state.advisorReducer.partyStatusList,
    productList: state.advisorReducer.productList,
    allServiceAndBrand: state.advisorReducer.allServiceAndBrand,
    remunerationList: state.advisorReducer.remunerationList,
    riskQuestionaireList: state.advisorReducer.riskQuestionaireList,
    roleList: state.advisorReducer.roleList,
    serviceList: state.advisorReducer.serviceList,
    allStateCityPincode: state.advisorReducer.allStateCityPincode,
    loading: state.appStateReducer.isLoading,
    uploadFileDetails: state.uploadFileReducer.uploadFileDetails,
    citySearch: state.advisorReducer.citySearch,
    publicAdvisorDetails: state.publicAdvisorReducer.publicAdvisorDetails,
    dashboard: state.advisorReducer.dashboard
});
