export const APP_STATE = {
    CHANGE_LOADING: 'CHANGE_LOADING'
};

export const ENVIRONMENT = {
    GET_ENVIRONMENT: 'GET_ENVIRONMENT'
};

export const LOGIN = {
    LOGGED_USER_DETAILS: 'LOGGED_USER_DETAILS',
    LOGIN_REQUESTING: 'LOGIN_REQUESTING',
    REFRESH_TOKEN: 'REFRESH_TOKEN'
};
export const SIGNUP = {
    SIGNUP_USER_DETAILS: 'SIGNED_USER_DETAILS',
    SIGNUP_REQUESTING: 'SIGNUP_REQUESTING',
    VALIDATE_UNIQUE_FIELDS: 'VALIDATE_UNIQUE_FIELDS',
    VALIDATE_UNIQUE_FIELDS_SUCCESS: 'VALIDATE_UNIQUE_FIELDS_SUCCESS'
};
export const TEAM_SIGNUP = {
    TEAM_CREATION_USER_DETAILS: 'TEAM_CREATION_USER_DETAILS',
    TEAM_CREATION_REQUESTING: 'TEAM_CREATION_REQUESTING',
    KEYPEOPLE_CREATION_USER_DETAILS: 'KEYPEOPLE_CREATION_USER_DETAILS',
    KEYPEOPLE_CREATION_REQUESTING: 'KEYPEOPLE_CREATION_REQUESTING',
    TEAM_MEMBER_DETAILS: 'TEAM_MEMBER_DETAILS',
    TEAM_MEMBER_SUCCESS: 'TEAM_MEMBER_SUCCESS',
    KEY_PEOPLE_DETAILS: 'KEY_PEOPLE_DETAILS',
    KEY_PEOPLE_SUCCESS: 'KEY_PEOPLE_SUCCESS',
    TEAM_MEMBER_DEACTIVATE: 'TEAM_MEMBER_DEACTIVATE',
    TEAM_MEMBER_DEACTIVATE_SUCCESS: 'TEAM_MEMBER_DEACTIVATE_SUCCESS',
    KEY_PEOPLE_DELETE: 'KEY_PEOPLE_DELETE',
    KEY_PEOPLE_DELETE_SUCCESS: 'KEY_PEOPLE_DELETE_SUCCESS',
    MODIFY_KEY_PEOPLE: 'MODIFY_KEY_PEOPLE',
    MODIFY_KEY_PEOPLE_SUCCESS: 'MODIFY_KEY_PEOPEL_SUCCESS',
    VALIDATE_UNIQUE_FIELDS: 'VALIDATE_UNIQUE_FIELDS',
    VALIDATE_UNIQUE_FIELDS_SUCCESS: 'VALIDATE_UNIQUE_FIELDS_SUCCESS'
};
export const ADVISOR = {
    ADVISOR_BRAND_INFO: 'ADVISOR_BRAND_DETAILS',
    ADVISOR_BRAND_INFO_SUCCESS: 'ADVISOR.ADVISOR_BRAND_DETAILS_SUCCESS',
    ADVISOR_PERSONAL_INFO: 'ADVISOR_PERSONAL_DETAILS',
    ADVISOR_PERSONAL_INFO_SUCCESS: 'ADVISOR_PERSONAL_DETAILS_SUCCESS',
    ADVISOR_PROD_INFO: 'ADVISOR_PROD_DETAILS',
    ADVISOR_PROD_INFO_SUCCESS: 'ADVISOR_PROD_DETAILS_SUCCESS',
    ADVISOR_PROFESSIONAL_INFO: 'ADVISOR_PROFESSIONAL_DETAILS',
    ADVISOR_PROFESSIONAL_INFO_SUCCESS: 'ADVISOR_PROFESSIONAL_DETAILS_SUCCESS',
    ADVISOR_VIDEO: 'ADVISOR_VIDEO_DETAILS',
    ADVISOR_VIDEO_SUCCESS: 'ADVISOR_VIDEO_DETAILS_SUCCESS'
};
export const FETCH_ADVISOR = {
    FETCH_BY_ADVISOR_ID: 'FETCH_BY_ADVISOR_ID',
    FETCH_BY_ADVISOR_ID_SUCCESS: 'FETCH_BY_ADVISOR_ID_SUCCESS',
    FETCH_BY_PUBLIC_ADVISOR_ID: 'FETCH_BY_PUBLIC_ADVISOR_ID',
    FETCH_BY_PUBLIC_ADVISOR_ID_SUCCESS: 'FETCH_BY_PUBLIC_ADVISOR_ID_SUCCESS',
    FETCH_ADVISOR_LIST: 'FETCH_ADVISOR_LIST',
    FETCH_ADVISOR_LIST_SUCCESS: 'FETCH_ADVISOR_LIST_SUCCESS',
    FETCH_BRAND_LIST: 'FETCH_BRAND_LIST',
    FETCH_BRAND_LIST_SUCCESS: 'FETCH_BRAND_LIST_SUCCESS',
    FETCH_CATEGORY_LIST: 'FETCH_CATEGORY_LIST',
    FETCH_CATEGORY_LIST_SUCCESS: 'FETCH_CATEGORY_LIST_SUCCESS',
    FETCH_CATEGORY_TYPE_LIST: 'FETCH_CATEGORY_TYPE_LIST',
    FETCH_CATEGORY_TYPE_LIST_SUCCESS: 'FETCH_CATEGORY_TYPE_LIST_SUCCESS',
    FETCH_FORUM_CATEGORY_LIST: 'FETCH_FORUM_CATEGORY_LIST',
    FETCH_FORUM_CATEGORY_LIST_SUCCESS: 'FETCH_FORUM_CATEGORY_LIST_SUCCESS',
    FETCH_FORUM_STATUS_LIST: 'FETCH_FORUM_STATUS_LIST',
    FETCH_FORUM_STATUS_LIST_SUCCESS: 'FETCH_FORUM_STATUS_LIST_SUCCESS',
    FETCH_FORUM_SUB_CATEGORY_LIST: 'FETCH_FORUM_SUB_CATEGORY_LIST',
    FETCH_FORUM_SUB_CATEGORY_LIST_SUCCESS: 'FETCH_FORUM_SUB_CATEGORY_LIST_SUCCESS',
    FETCH_GOALS_SERVED_LIST: 'FETCH_GOALS_SERVED_LIST',
    FETCH_LICENSE_LIST: 'FETCH_LICENSE_LIST',
    FETCH_LICENSE_LIST_SUCCESS: 'FETCH_LICENSE_LIST_SUCCESS',
    FETCH_PARTY_STATUS_LIST: 'FETCH_PARTY_STATUS_LIST',
    FETCH_PARTY_STATUS_LIST_SUCCESS: 'FETCH_PARTY_STATUS_LIST_SUCCESS',
    FETCH_PRODUCT_LIST: 'FETCH_PRODUCT_LIST',
    FETCH_PRODUCT_LIST_SUCCESS: 'FETCH_PRODUCT_LIST_SUCCESS',
    FETCH_ALL_SERVICE_AND_BRAND: 'FETCH_ALL_SERVICE_AND_BRAND',
    FETCH_ALL_SERVICE_AND_BRAND_SUCCESS: 'FETCH_ALL_SERVICE_AND_BRAND_SUCCESS',
    FETCH_REMUNERATION_LIST: 'FETCH_RENUMERATION_LIST',
    FETCH_REMUNERATION_LIST_SUCCESS: 'FETCH_REMUNERATION_LIST_SUCCESS',
    FETCH_RISK_QUESTIONAIRE_LIST: 'FETCH_RISK_QUESTIONAIRE_LIST',
    FETCH_RISK_QUESTIONAIRE_LIST_SUCCESS: 'FETCH_RISK_QUESTIONAIRE_LIST_SUCCESS',
    FETCH_ROLE_LIST: 'FETCH_ROLE_LIST',
    FETCH_ROLE_LIST_SUCCESS: 'FETCH_ROLE_LIST_SUCCESS',
    FETCH_SERVICE_LIST: 'FETCH_SERVICE_LIST',
    FETCH_SERVICE_LIST_SUCCESS: 'FETCH_SERVICE_LIST_SUCCESS',
    FETCH_SPECIALISED_SKILLS: 'FETCH_SPECIALISED_SKILLS',
    FETCH_ALL_STATE_CITY_PINCODE: 'FETCH_ALL_STATE_CITY_PINCODE',
    FETCH_ALL_STATE_CITY_PINCODE_USER: 'FETCH_ALL_STATE_CITY_PINCODE_USER',
    FETCH_ALL_STATE_CITY_PINCODE_SUCCESS: 'FETCH_ALL_STATE_CITY_PINCODE_SUCCESS',
    FETCH_ADV_BRAND_RANK_BY_ADV_ID: 'FETCH_ADV_BRAND_RANK_BY_ADV_ID',
    FETCH_ADV_BRAND_RANK_BY_ADV_ID_SUCCESS: 'FETCH_ADV_BRAND_RANK_BY_ADV_ID_SUCCESS',
    FETCH_ACCOUNT_LIST: 'FETCH_ACCOUNT_LIST',
    FETCH_ACCOUNT_TYPE_LIST: 'FETCH_ACCOUNT_TYPE_LIST',
    FETCH_CASH_FLOW_ITEM_LIST: 'FETCH_CASH_FLOW_ITEM_LIST',
    FETCH_CASH_FLOW_ITEM_TYPE_LIST: 'FETCH_CASH_FLOW_ITEM_TYPE_LIST',
    FETCH_PRIORITY_ITEM_LIST: 'FETCH_PRIORITY_ITEM_LIST',
    FETCH_RISK_PORTFOLIO_LIST: 'FETCH_RISK_PORTFOLIO_LIST',
    FETCH_URGENCY_LIST_: 'FETCH_URGENCY_LIST',
    DELETE_ADVISOR: 'DELETE_ADVISOR',
    DELETE_ADVISOR_SUCCESS: 'DELETE_ADVISOR_SUCCESS',
    MODIFY_ADVISOR: 'MODIFY_ADVISOR',
    MODIFY_ADVISOR_SUCCESS: 'MODIFY_ADVISOR_SUCCESS',
    MODIFY_ADVISOR_PRODUCT: 'MODIFY_ADVISOR_PRODUCT',
    MODIFY_ADVISOR_PRODUCT_SUCCESS: 'MODIFY_ADVISOR_PRODUCT_SUCCESS',
    MODIFY_ADV_PROFESSIONAL_INFO: 'MODIFY_ADV_PROFESSIONAL_INFO',
    MODIFY_ADV_PROFESSIONAL_INFO_SUCCESS: 'MODIFY_ADV_PROFESSIONAL_INFO_SUCCESS',
    CHANGE_PASSWORD: 'CHANGE_PASSWORD',
    CHANGE_PASSWORD_SUCCESS: 'CHANGE_PASSWORD_SUCCESS',
    FETCH_ALL_ADVISOR_CONSTANTS: 'FETCH_ALL_ADVISOR_CONSTANTS',
    ADVISOR_LOADING: 'ADVISOR_LOADING',
    UPDATE_ADVISOR_WORKFLOW: 'UPDATE_ADVISOR_WORKFLOW',
    SEARCH_CITY: 'SEARCH_CITY',
    SEARCH_CITY_SUCCESS: 'SEARCH_CITY_SUCCESS',
    FETCH_DASHBOARD_COUNT: 'FETCH_DASHBOARD_COUNT',
    FETCH_DASHBOARD_COUNT_SUCCESS: 'FETCH_DASHBOARD_COUNT_SUCCESS',
    VALIDATE_PASSWORD: 'VALIDATE_PASSWORD',
    VALIDATE_PASSWORD_SUCCESS: 'VALIDATE_PASSWORD_SUCCESS',
    CLEAR_VALIDATE_PASSWORD: 'CLEAR_VALIDATE_PASSWORD'
};

export const PLANNING = {
    FETCH_FINANCIAL_PLANNING: 'FETCH_FINANCIAL_PLANNING',
    FETCH_FINANCIAL_PLANNING_SUCCESS: 'FETCH_FINANCIAL_PLANNING_SUCCESS',
    FETCH_LOAN_PLANNING: 'FETCH_LOAN_PLANNING',
    FETCH_LOAN_PLANNING_SUCCESS: 'FETCH_LOAN_PLANNING_SUCCESS',
    FETCH_INVESTMENT_PLANNING: 'FETCH_INVESTMENT_PLANNING',
    FETCH_INVESTMENT_PLANNING_SUCCESS: 'FETCH_INVESTMENT_PLANNING_SUCCESS',
    FETCH_RISK_PLANNING: 'FETCH_RISK_PLANNING',
    FETCH_RISK_PLANNING_SUCCESS: 'FETCH_RISK_PLANNING_SUCCESS',
    FETCH_RISK_QUESTIONAIRE: 'FETCH_RISK_QUESTIONAIRE',
    FETCH_RISK_QUESTIONAIRE_SUCCESS: 'FETCH_RISK_QUESTIONAIRE_SUCCESS',
    FETCH_PLAN_BY_REFERENCE: 'FETCH_PLAN_BY_REFERENCE',
    FETCH_PLAN_BY_REFERENCE_SUCCESS: 'FETCH_PLAN_BY_REFERENCE_SUCCESS',
    FETCH_PLAN_BY_PARTYID: 'FETCH_PLAN_BY_PARTYID',
    FETCH_PLAN_BY_PARTYID_SUCCESS: 'FETCH_PLAN_BY_PARTYID_SUCCESS',
    CALCULATE_CASHFLOW: 'CALCULATE_CASHFLOW',
    CALCULATE_CASHFLOW_SUCCESS: 'CALCULATE_CASHFLOW_SUCCESS',
    CALCULATE_NETWORTH: 'CALCULATE_NETWORTH',
    CALCULATE_NETWORTH_SUCCESS: 'CALCULATE_NETWORTH_SUCCESS',
    CALCULATE_PRIORITIES: 'CALCULATE_PRIORITIES',
    CALCULATE_PRIORITIES_SUCCESS: 'CALCULATE_PRIORITIES_SUCCESS',
    CALCULATE_INSURANCE: 'CALCULATE_INSURANCE',
    CALCULATE_INSURANCE_SUCCESS: 'CALCULATE_INSURANCE_SUCCESS',
    CALCULATE_RISK_PROFILE: 'CALCULATE_RISK_PROFILE',
    CALCULATE_RISK_PROFILE_SUCCESS: 'CALCULATE_RISK_PROFILE_SUCCESS',
    ADD_PLAN: 'ADD_PLAN',
    ADD_PLAN_SUCCESS: 'ADD_PLAN_SUCCESS',
    MODIFY_PLAN: 'MODIFY_PLAN',
    MODIFY_PLAN_SUCCESS: 'MODIFY_PLAN_SUCCESS',
    DELETE_PLAN: 'DELETE_PLAN',
    DELETE_PLAN_SUCCESS: 'DELETE_PLAN_SUCCESS',
    DOWNLOAD_PLANS_PDF: 'DOWNLOAD_PLANS_PDF',
    CLEAR_CASHFLOW_VALUE: 'CLEAR_CASHFLOW_VALUE',
    CLEAR_NETWORTH_VALUE: 'CLEAR_NETWORTH_VALUE',
    CLEAR_PRIORITIES_VALUE: 'CLEAR_PRIORITIES_VALUE',
    CLEAR_INSURANCE_VALUE: 'CLEAR_INSURANCE_VALUE'
};
export const BLOG = {
    CREATE_ARTICLE_POST: 'CREATE_ARTICLE_POST',
    CREATE_ARTICLE_POST_SUCCESS: 'CREATE_ARTICLE_POST_SUCCESS',
    CREATE_ARTICLE_POST_COMMENT: 'CREATE_ARTICLE_POST_COMMENT',
    CREATE_ARTICLE_POST_COMMENT_SUCCESS: 'CREATE_ARTICLE_POST_COMMENT_SUCCESS',
    FETCH_ARTICLE_COMMENT: 'FETCH_ARTICLE_COMMENT',
    FETCH_ARTICLE_COMMENT_SUCCESS: 'FETCH_ARTICLE_COMMENT_SUCCESS',
    FETCH_ARTICLE_LIST_BY_PARTY_ID: 'FETCH_ARTICLE_LIST_BY_PARTY_ID',
    FETCH_ARTICLE_LIST_BY_PARTY_ID_SUCCESS: 'FETCH_ARTICLE_LIST_BY_PARTY_ID_SUCCESS',
    FETCH_ARTICLE_POST_BY_ARTICLE: 'FETCH_ARTICLE_POST_BY_ARTICLE',
    FETCH_ARTICLE_POST_BY_ARTICLE_SUCCESS: 'FETCH_ARTICLE_POST_BY_ARTICLE_SUCCESS',
    CREATE_ARTICLE_VOTE: 'CREATE_ARTICLE_VOTE',
    CREATE_ARTICLE_VOTE_SUCCESS: 'CREATE_ARTICLE_VOTE_SUCCESS',

    CHANGE_ARTICLE_STATUS: 'CHANGE_ARTICLE_STATUS',
    CHANGE_ARTICLE_STATUS_SUCCESS: 'CHANGE_ARTICLE_STATUS_SUCCESS',
    FETCH_ARTICLE_POST: 'FETCH_ARTICLE_POST',
    FETCH_ARTICLE_POST_SUCCESS: 'FETCH_ARTICLE_POST_SUCCESS',
    FETCH_ALL_ARTICLE_IN_APPROVED_ORDER: 'FETCH_ALL_ARTICLE_IN_APPROVED_ORDER',
    FETCH_ALL_ARTICLE_IN_APPROVED_ORDER_SUCCESS: 'FETCH_ALL_ARTICLE_IN_APPROVED_ORDER_SUCCESS',
    FETCH_ALL_FORUM_CATEGORY: 'FETCH_ALL_FORUM_CATEGORY',
    FETCH_ALL_FORUM_CATEGORY_SUCCESS: 'FETCH_ALL_FORUM_CATEGORY_SUCCESS',
    FETCH_RECENT_ARTICLE_POST_LIST: 'FETCH_RECENT_ARTICLE_POST_LIST',
    FETCH_RECENT_ARTICLE_POST_LIST_SUCCESS: 'FETCH_RECENT_ARTICLE_POST_LIST_SUCCESS',
    FECTH_RECENT_APPROVED_ARTICLE: 'FECTH_RECENT_APPROVED_ARTICLE',
    FECTH_RECENT_APPROVED_ARTICLE_SUCCESS: 'FECTH_RECENT_APPROVED_ARTICLE_SUCCESS',
    MODERATE_ARTICLE_POST: 'MODERATE_ARTICLE_POST',
    MODERATE_ARTICLE_POST_SUCCESS: 'MODERATE_ARTICLE_POST_SUCCESS',
    MODERATE_ARTICLE_POST_COMMENT: 'MODERATE_ARTICLE_POST_COMMENT',
    MODERATE_ARTICLE_POST_COMMENT_SUCCESS: 'MODERATE_ARTICLE_POST_COMMENT_SUCCESS',
    DELETE_ARTICLE: 'DELETE_ARTICLE',
    DELETE_ARTICLE_SUCCESS: 'DELETE_ARTICLE_SUCCESS',
    DELETE_ARTICLE_COMMENT: 'DELETE_ARTICLE_COMMENT',
    DELETE_ARTICLE_COMMENT_SUCCESS: 'DELETE_ARTICLE_COMMENT_SUCCESS',
    FETCH_FAVOURITE_ARTICLES_BY_PARTY_ID: 'FETCH_FAVOURITE_ARTICLES_BY_PARTY_ID',
    FETCH_FAVOURITE_ARTICLES_BY_PARTY_ID_SUCCESS: 'FETCH_FAVOURITE_ARTICLES_BY_PARTY_ID_SUCCESS',
    ADD_ARTICLE_TO_FAVORITE: 'ADD_ARTICLE_TO_FAVORITE',
    ADD_ARTICLE_TO_FAVORITE_SUCCESS: 'ADD_ARTICLE_TO_FAVORITE_SUCCESS',
    FETCH_ARTICLE_UPCOUNT: 'FETCH_ARTICLE_UPCOUNT',
    FETCH_ARTICLE_UPCOUNT_SUCCESS: 'FETCH_ARTICLE_UPCOUNT_SUCCESS'
};

export const MY_GOAL = {
    FETCH_GOAL_PLANNING: 'FETCH_GOAL_PLANNING',
    FETCH_GOAL_PLANNING_RESPONSE: 'FETCH_GOAL_PLANNING_RESPONSE',
    ON_VALUE_CHANGE: 'GOAL_ON_VALUE_CHANGE',
    ON_VALUE_CHANGE_SUCCESS: 'GOAL_ON_VALUE_CHANGE_SUCCESS',
    CALCULATE_REQUEST: 'GOAL_CALCULATE_REQUEST',
    CALCULATE_RESPONSE: 'GOAL_CALCULATE_RESPONSE',
    RESET: 'GOAL_RESET',
    CLEAR_GOALVALUE: 'CLEAR_GOALVALUE'
};

export const EMI_CALCULATOR = {
    ON_VALUE_CHANGE: 'EMI_ON_VALUE_CHANGE',
    ON_VALUE_CHANGE_SUCCESS: 'EMI_ON_VALUE_CHANGE_SUCCESS',
    CALCULATE_EMI_REQUEST: 'CALCULATE_EMI_REQUEST',
    CALCULATE_EMI_RESPONSE: 'CALCULATE_EMI_RESPONSE',
    CHANGE_EMI_CALCULATOR_BUTTON_CLICKED: 'CHANGE_EMI_CALCULATOR_BUTTON_CLICKED',
    CLEAR_EMI_CALCULATOR: 'CLEAR_EMI_CALCULATOR',
    CALCULATE_SHARE_REQUEST: 'CALCULATE_EMI_SHARE_REQUEST'
};

export const EMI_CAPACITY = {
    ON_VALUE_CHANGE: 'EMI_CAPACITY_ON_VALUE_CHANGE',
    ON_VALUE_CHANGE_SUCCESS: 'EMI_CAPACITY_ON_VALUE_CHANGE_SUCCESS',
    CALCULATE_EMI_CAPACITY_REQUEST: 'CALCULATE_EMI_CAPACITY_REQUEST',
    CALCULATE_EMI_CAPACITY_RESPONSE: 'CALCULATE_EMI_CAPACITY_RESPONSE',
    CHANGE_EMI_CAPACITY_BUTTON_CLICKED: 'CHANGE_EMI_CAPACITY_BUTTON_CLICKED',
    CLEAR_EMI_CAPACITY: 'CLEAR_EMI_CAPACITY',
    CALCULATE_SHARE_REQUEST: 'CALCULATE_SHARE_REQUEST'
};

export const PARTIAL_PAYMENTS = {
    ON_VALUE_CHANGE: 'PARTIAL_PAYMENTS_ON_VALUE_CHANGE',
    ON_VALUE_CHANGE_SUCCESS: 'PARTIAL_PAYMENTS_ON_VALUE_CHANGE_SUCCESS',
    CALCULATE_PARTIAL_PAYMENTS_REQUEST: 'CALCULATE_PARTIAL_PAYMENTS_REQUEST',
    CALCULATE_PARTIAL_PAYMENTS_REQUEST_START: 'CALCULATE_PARTIAL_PAYMENTS_REQUEST_START',
    CALCULATE_PARTIAL_PAYMENTS_RESPONSE: 'CALCULATE_PARTIAL_PAYMENTS_RESPONSE',
    CHANGE_PARTIAL_PAYMENTS_BUTTON_CLICKED: 'CHANGE_PARTIAL_PAYMENTS_BUTTON_CLICKED',
    CLEAR_PARTIAL_PAYMENTS: 'CLEAR_PARTIAL_PAYMENTS',
    CALCULATE_SHARE_REQUEST: 'CALCULATE_SHARE_REQUEST'
};

export const CHANGE_IN_EMI = {
    ON_VALUE_CHANGE: 'EMI_CHANGE_ON_VALUE_CHANGE',
    ON_VALUE_CHANGE_SUCCESS: 'EMI_CHANGE_ON_VALUE_CHANGE_SUCCESS',
    CALCULATE_EMI_CHANGE_REQUEST: 'CALCULATE_EMI_CHANGE_REQUEST',
    CALCULATE_EMI_CHANGE_REQUEST_START: 'CALCULATE_EMI_CHANGE_START',
    CALCULATE_EMI_CHANGE_RESPONSE: 'CALCULATE_EMI_CHANGE_RESPONSE',
    CHANGE_IN_EMI_BUTTON_CLICKED: 'CHANGE_IN_EMI_BUTTON_CLICKED',
    CLEAR_CHANGE_IN_EMI: 'CLEAR_CHANGE_IN_EMI',
    CALCULATE_SHARE_REQUEST: 'CALCULATE_SHARE_REQUEST'
};

export const CHANGE_IN_INTEREST = {
    ON_VALUE_CHANGE: 'INTEREST_CHANGE_ON_VALUE_CHANGE',
    ON_VALUE_CHANGE_SUCCESS: 'INTEREST_CHANGE_ON_VALUE_CHANGE_SUCCESS',
    CALCULATE_INTEREST_CHANGE_REQUEST: 'CALCULATE_INTEREST_CHANGE',
    CALCULATE_INTEREST_CHANGE_REQUEST_START: 'CALCULATE_INTEREST_CHANGE_START',
    CALCULATE_INTEREST_CHANGE_RESPONSE: 'CALCULATE_INTEREST_CHANGE_RESPONSE',
    CHANGE_IN_INTEREST_BUTTON_CLICKED: 'CHANGE_IN_INTEREST_BUTTON_CLICKED',
    CLEAR_CHANGE_IN_INTEREST: 'CLEAR_CHANGE_IN_INTEREST',
    CALCULATE_SHARE_REQUEST: 'CALCULATE_SHARE_REQUEST'
};

export const INVESTOR = {
    ADD_INV_INTEREST: 'ADD_INV_INTEREST',
    ADD_INV_INTEREST_SUCCESS: 'ADD_INV_INTEREST_SUCCESS',
    FETCH_INVESTOR_LIST: 'FETCH_INVESTOR_LIST',
    FETCH_INVESTOR_LIST_SUCCESS: 'FETCH_INVESTOR_LIST_SUCCESS',
    FETCH_BY_INVESTOR_ID: 'FETCH_BY_INVESTOR_ID',
    FETCH_BY_INVESTOR_ID_SUCCESS: 'FETCH_BY_INVESTOR_ID_SUCCESS',
    MODIFY_INVESTOR: 'MODIFY_INVESTOR',
    MODIFY_INVESTOR_SUCCESS: 'MODIFY_INVESTOR_SUCCESS',
    MODIFY_INV_INTEREST: 'MODIFY_INV_INTEREST',
    MODIFY_INV_INTEREST_SUCCESS: 'MODIFY_INV_INTEREST_SUCCESS',
    DELETE_INVESTOR: 'DELETE_INVESTOR',
    DELETE_INVESTOR_SUCCESS: 'DELETE_INVESTOR_SUCCESS',
    DELETE_INV_INTEREST: 'DELETE_INV_INTEREST',
    DELETE_INV_INTEREST_SUCCESS: 'DELETE_INV_INTEREST_SUCCESS'
};

export const UPLOADFILE = {
    UPLOAD_FILE: 'UPLOAD_FILE',
    UPLOAD_FILE_SUCCESS: 'UPLOAD_FILE_SUCCESS',
    CLEAR_IMAGE: 'CLEAR_IMAGE'
};

export const VERIFYSIGNUP = {
    VERIFY_SIGNUP: 'VERIFY_SIGNUP',
    VERIFY_SIGNUP_SUCCESS: 'VERIFY_SIGNUP_SUCCESS'
};

export const PROMOTIONS = {
    ADD_PROMOTIONS: 'ADD_PROMOTIONS',
    ADD_PROMOTIONS_SUCCESS: 'ADD_PROMOTIONS_SUCCESS'
};

export const DELETEFILE = {
    DELETE_FILE: 'DELETE_FILE'
};

export const PROFILE = {
    GET_PROFILE: 'GET_PROFILE',
    GET_PROFILE_SUCCESS: 'GET_PROFILE_SUCCESS',
    GET_PROFILE_ERROR: 'GET_PROFILE_ERROR',
    UPDATE_PROFILE: 'UPDATE_PROFILE',
    UPDATE_INVESTOR_PROFILE: 'UPDATE_INVESTOR_PROFILE',
    GET_PROFILE_WITHOUT_TOKEN: 'GET_PROFILE_WITHOUT_TOKEN',
    GET_PROFILE_BY_USERNAME: 'GET_PROFILE_BY_USERNAME',
    CLEAR_PROFILE: 'CLEAR_PROFILE'
};

export const FUTURE_VALUE = {
    ON_VALUE_CHANGE: 'FUTURE_VALUE_ON_VALUE_CHANGE',
    ON_VALUE_CHANGE_SUCCESS: 'FUTURE_VALUE_ON_VALUE_CHANGE_SUCCESS',
    CALCULATE_REQUEST: 'FUTURE_VALUE_CALCULATE',
    CALCULATE_SHARE_REQUEST: 'FUTURE_VALUE_SHARE_CALCULATE',
    CALCULATE_RESPONSE: 'FUTURE_VALUE_CALCULATE_RESPONSE',
    CLEAR_FUTUREVALUE: 'CLEAR_FUTUREVALUE'
};

export const TARGET_VALUE = {
    ON_VALUE_CHANGE: 'TARGET_VALUE_ON_VALUE_CHANGE',
    ON_VALUE_CHANGE_SUCCESS: 'TARGET_VALUE_ON_VALUE_CHANGE_SUCCESS',
    CALCULATE_REQUEST: 'TARGET_VALUE_CALCULATE',
    CALCULATE_SHARE_REQUEST: 'TARGET_VALUE_SHARE_CALCULATE',
    CALCULATE_RESPONSE: 'TARGET_VALUE_CALCULATE_RESPONSE',
    CLEAR_TARGETVALUE: 'CLEAR_TARGETVALUE'
};

export const RATE_FINDER = {
    ON_VALUE_CHANGE: 'RATE_FINDER_ON_VALUE_CHANGE',
    ON_VALUE_CHANGE_SUCCESS: 'RATE_FINDER_ON_VALUE_CHANGE_SUCCESS',
    CALCULATE_REQUEST: 'RATE_FINDER_CALCULATE',
    CALCULATE_SHARE_REQUEST: 'RATE_FINDER_SHARE_CALCULATE',
    CALCULATE_RESPONSE: 'RATE_FINDER_CALCULATE_RESPONSE',
    CLEAR_RATEFINDER: 'CLEAR_RATEFINDER'
};

export const TENURE_FINDER = {
    ON_VALUE_CHANGE: 'TENURE_FINDER_ON_VALUE_CHANGE',
    ON_VALUE_CHANGE_SUCCESS: 'TENURE_FINDER_ON_VALUE_CHANGE_SUCCESS',
    CALCULATE_REQUEST: 'TENURE_FINDER_CALCULATE',
    CALCULATE_SHARE_REQUEST: 'TENURE_FINDER_SHARE_CALCULATE',
    CALCULATE_RESPONSE: 'TENURE_FINDER_CALCULATE_RESPONSE',
    CLEAR_TENUREFINDER: 'CLEAR_TENUREFINDER'
};

export const RESETPASSWORD = {
    RESET_PASSWORD: 'RESET_PASSWORD',
    RESET_PASSWORD_SUCCESS: 'RESET_PASSWORD_SUCCESS'
};

export const FORGETPASSWORD = {
    FORGET_PASSWORD: 'FORGET_PASSWORD',
    FORGET_PASSWORD_SUCCESS: 'FORGET_PASSWORD_SUCCESS'
};

export const RESENDMAIL = {
    RESEND_MAIL: 'RESEND_MAIL',
    RESEND_MAIL_SUCCESS: 'RESEND_MAIL_SUCCESS'
};

export const EXPLORE = {
    EXPLORE_BY_USER: 'EXPLORE_BY_USER',
    EXPLORE_BY_USER_SUCCESS: 'EXPLORE_BY_USER_SUCCESS',
    EXPLORE_BY_PRODUCTS: 'EXPLORE_BY_PRODUCTS'
};

export const VERIFYOTP = {
    VERIFY_OTP: 'VERIFY_OTP',
    OTP_VERIFIED_SUCCESS: 'OTP_VERIFIED_SUCCESS',
    CLEAR_MESSAGE: 'CLEAR_MESSAGE'
};

export const SENDOTP = {
    SEND_OTP: 'SEND_OTP',
    SEND_OTP_SUCCESS: 'SEND_OTP_SUCCESS'
};

export const MEMBERSHIP = {
    UPDATE_SUBSCRIPTION: 'UPDATE_SUBSCRIPTION',
    UPDATE_SUBSCRIPTION_SUCCESS: 'UPDATE_SUBSCRIPTION_SUCCESS',
    FETCH_ALL_MEMBERSHIP_PLAN: 'FETCH_ALL_MEMBERSHIP_PLAN',
    FETCH_ALL_MEMBERSHIP_PLAN_SUCCESS: 'FETCH_ALL_MEMBERSHIP_PLAN_SUCCESS',
    CREATE_SUBSCRIPTION: 'CREATE_SUBSCRIPTION',
    CREATE_SUBSCRIPTION_SUCCESS: 'CREATE_SUBSCRIPTION_SUCCESS',
    CANCEL_SUBSCRIPTION: 'CANCEL_SUBSCRIPTION',
    CANCEL_SUBSCRIPTION_SUCCESS: 'CANCEL_SUBSCRIPTION_SUCCESS',
    CREATE_SINGLE_PAYMENT_ORDER: 'CREATE_SINGLE_PAYMENT_ORDER',
    CREATE_SINGLE_PAYMENT_ORDER_SUCCESS: 'CREATE_SINGLE_PAYMENT_ORDER_SUCCESS',
    VERIFY_SINGLE_PAYMENT: 'VERIFY_SINGLE_PAYMENT',
    VERIFY_SINGLE_PAYMENT_SUCCESS: 'VERIFY_SINGLE_PAYMENT_SUCCESS',
    VERIFY_SUBSCRIPTION: 'VERIFY_SUBSCRIPTION',
    VERIFY_SUBSCRIPTION_SUCCESS: 'VERIFY_SUBSCRIPTION_SUCCESS',
    FETCH_SUBSCRIPTION: 'FETCH_SUBSCRIPTION',
    FETCH_SUBSCRIPTION_SUCCESS: 'FETCH_SUBSCRIPTION_SUCCESS',
    CREATE_ORDER_NUMBER: 'CREATE_ORDER_NUMBER',
    CREATE_ORDER_NUMBER_SUCCESS: 'CREATE_ORDER_NUMBER_SUCCESS',
    UPDATE_ORDER_DETAIL: 'UPDATE_ORDER_DETAIL',
    UPDATE_ORDER_DETAIL_SUCCESS: 'UPDATE_ORDER_DETAIL_SUCCESS',
    ON_PAID: 'ON_PAID'
};

export const CALCQUERY = {
    CREATE_CALC_QUERY: 'CREATE_CALC_QUERY',
    CREATE_CALC_QUERY_SUCCESS: 'CREATE_CALC_QUERY_SUCCESS',
    FETCH_SHARED_PLAN_BY_POSTEDPARTYID: 'FETCH_SHARED_PLAN_BY_POSTEDPARTYID',
    FETCH_SHARED_PLAN_BY_POSTEDPARTYID_SUCCESS: 'FETCH_SHARED_PLAN_BY_POSTEDPARTYID_SUCCESS',
    FETCH_SHARED_BY_PARTY_Id_AND_REF_ID: 'FETCH_SHARED_BY_PARTY_Id_AND_REF_ID',
    FETCH_SHARED_BY_PARTY_Id_AND_REF_ID_SUCCESS: 'FETCH_SHARED_BY_PARTY_Id_AND_REF_ID_SUCCESS',
    FETCH_SHARED_BY_REF_ID: 'FETCH_SHARED_BY_REF_ID',
    FETCH_SHARED_BY_REF_ID_SUCCESS: 'FETCH_SHARED_BY_REF_ID_SUCCESS',
    COMMENT_QUERIES: 'COMMENT_QUERIES',
    COMMENT_QUERIES_SUCCESS: 'COMMENT_QUERIES_SUCCESS',
    CREATE_CALC_ANSWER: 'CREATE_CALC_ANSWER',
    CREATE_CALC_ANSWER_SUCCESS: 'CREATE_CALC_ANSWER_SUCCESS',
    FETCH_QUERIES: 'FETCH_QUERIES',
    FETCH_QUERIES_SUCCESS: 'FETCH_QUERIES_SUCCESS',
    FETCH_CALC_ANSWER: 'FETCH_CALC_ANSWER',
    FETCH_CALC_ANSWER_SUCCESS: 'FETCH_CALC_ANSWER_SUCCESS',
    CLEAR_FETCH_QUERIES: 'CLEAR_FETCH_QUERIES',
    CLEAR_FETCH_SHARED_BY_REF_ID: 'CLEAR_FETCH_SHARED_BY_REF_ID'
};
